/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSystemHealthRouteImport } from './routes/_app.system-health'
import { Route as AppStockTransfersRouteImport } from './routes/_app.stock-transfers'
import { Route as AppStockAdjustmentRouteImport } from './routes/_app.stock-adjustment'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPricingPlansRouteImport } from './routes/_app.pricing-plans'
import { Route as AppPayoutsRouteImport } from './routes/_app.payouts'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppPaymentPagesRouteImport } from './routes/_app.payment-pages'
import { Route as AppPaymentLinksRouteImport } from './routes/_app.payment-links'
import { Route as AppMobileControlRouteImport } from './routes/_app.mobile-control'
import { Route as AppMobileAppRouteImport } from './routes/_app.mobile-app'
import { Route as AppMarketingRouteImport } from './routes/_app.marketing'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDatabaseBackupRouteImport } from './routes/_app.database-backup'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppApiKeysRouteImport } from './routes/_app.api-keys'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAccessControlRouteImport } from './routes/_app.access-control'
import { Route as App2faRouteImport } from './routes/_app.2fa'
import { Route as AppReportsSalesRouteImport } from './routes/_app.reports.sales'
import { Route as AppReportsPurchasesRouteImport } from './routes/_app.reports.purchases'
import { Route as AppReportsProfitLossRouteImport } from './routes/_app.reports.profit-loss'
import { Route as AppReportsInventoryRouteImport } from './routes/_app.reports.inventory'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemHealthRoute = AppSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AppRoute,
} as any)
const AppStockTransfersRoute = AppStockTransfersRouteImport.update({
  id: '/stock-transfers',
  path: '/stock-transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockAdjustmentRoute = AppStockAdjustmentRouteImport.update({
  id: '/stock-adjustment',
  path: '/stock-adjustment',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingPlansRoute = AppPricingPlansRouteImport.update({
  id: '/pricing-plans',
  path: '/pricing-plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentPagesRoute = AppPaymentPagesRouteImport.update({
  id: '/payment-pages',
  path: '/payment-pages',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentLinksRoute = AppPaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileControlRoute = AppMobileControlRouteImport.update({
  id: '/mobile-control',
  path: '/mobile-control',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileAppRoute = AppMobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseBackupRoute = AppDatabaseBackupRouteImport.update({
  id: '/database-backup',
  path: '/database-backup',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessControlRoute = AppAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => AppRoute,
} as any)
const App2faRoute = App2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPurchasesRoute = AppReportsPurchasesRouteImport.update({
  id: '/reports/purchases',
  path: '/reports/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsProfitLossRoute = AppReportsProfitLossRouteImport.update({
  id: '/reports/profit-loss',
  path: '/reports/profit-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsInventoryRoute = AppReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/2fa': typeof App2faRoute
  '/access-control': typeof AppAccessControlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-keys': typeof AppApiKeysRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/database-backup': typeof AppDatabaseBackupRoute
  '/expenses': typeof AppExpensesRoute
  '/logs': typeof AppLogsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/marketing': typeof AppMarketingRoute
  '/mobile-app': typeof AppMobileAppRoute
  '/mobile-control': typeof AppMobileControlRoute
  '/payment-links': typeof AppPaymentLinksRoute
  '/payment-pages': typeof AppPaymentPagesRoute
  '/payments': typeof AppPaymentsRoute
  '/payouts': typeof AppPayoutsRoute
  '/pricing-plans': typeof AppPricingPlansRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/security': typeof AppSecurityRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/stock-adjustment': typeof AppStockAdjustmentRoute
  '/stock-transfers': typeof AppStockTransfersRoute
  '/system-health': typeof AppSystemHealthRoute
  '/transactions': typeof AppTransactionsRoute
  '/users': typeof AppUsersRoute
  '/webhooks': typeof AppWebhooksRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/sales': typeof AppReportsSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/2fa': typeof App2faRoute
  '/access-control': typeof AppAccessControlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-keys': typeof AppApiKeysRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/database-backup': typeof AppDatabaseBackupRoute
  '/expenses': typeof AppExpensesRoute
  '/logs': typeof AppLogsRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/marketing': typeof AppMarketingRoute
  '/mobile-app': typeof AppMobileAppRoute
  '/mobile-control': typeof AppMobileControlRoute
  '/payment-links': typeof AppPaymentLinksRoute
  '/payment-pages': typeof AppPaymentPagesRoute
  '/payments': typeof AppPaymentsRoute
  '/payouts': typeof AppPayoutsRoute
  '/pricing-plans': typeof AppPricingPlansRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/security': typeof AppSecurityRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/stock-adjustment': typeof AppStockAdjustmentRoute
  '/stock-transfers': typeof AppStockTransfersRoute
  '/system-health': typeof AppSystemHealthRoute
  '/transactions': typeof AppTransactionsRoute
  '/users': typeof AppUsersRoute
  '/webhooks': typeof AppWebhooksRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/sales': typeof AppReportsSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/2fa': typeof App2faRoute
  '/_app/access-control': typeof AppAccessControlRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/database-backup': typeof AppDatabaseBackupRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/mobile-app': typeof AppMobileAppRoute
  '/_app/mobile-control': typeof AppMobileControlRoute
  '/_app/payment-links': typeof AppPaymentLinksRoute
  '/_app/payment-pages': typeof AppPaymentPagesRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/pricing-plans': typeof AppPricingPlansRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stock-adjustment': typeof AppStockAdjustmentRoute
  '/_app/stock-transfers': typeof AppStockTransfersRoute
  '/_app/system-health': typeof AppSystemHealthRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/_app/reports/inventory': typeof AppReportsInventoryRoute
  '/_app/reports/profit-loss': typeof AppReportsProfitLossRoute
  '/_app/reports/purchases': typeof AppReportsPurchasesRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/2fa'
    | '/access-control'
    | '/analytics'
    | '/api-keys'
    | '/audit-logs'
    | '/contacts'
    | '/dashboard'
    | '/database-backup'
    | '/expenses'
    | '/logs'
    | '/maintenance'
    | '/marketing'
    | '/mobile-app'
    | '/mobile-control'
    | '/payment-links'
    | '/payment-pages'
    | '/payments'
    | '/payouts'
    | '/pricing-plans'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/security'
    | '/sessions'
    | '/settings'
    | '/stock-adjustment'
    | '/stock-transfers'
    | '/system-health'
    | '/transactions'
    | '/users'
    | '/webhooks'
    | '/reports/inventory'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/2fa'
    | '/access-control'
    | '/analytics'
    | '/api-keys'
    | '/audit-logs'
    | '/contacts'
    | '/dashboard'
    | '/database-backup'
    | '/expenses'
    | '/logs'
    | '/maintenance'
    | '/marketing'
    | '/mobile-app'
    | '/mobile-control'
    | '/payment-links'
    | '/payment-pages'
    | '/payments'
    | '/payouts'
    | '/pricing-plans'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/security'
    | '/sessions'
    | '/settings'
    | '/stock-adjustment'
    | '/stock-transfers'
    | '/system-health'
    | '/transactions'
    | '/users'
    | '/webhooks'
    | '/reports/inventory'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/2fa'
    | '/_app/access-control'
    | '/_app/analytics'
    | '/_app/api-keys'
    | '/_app/audit-logs'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/database-backup'
    | '/_app/expenses'
    | '/_app/logs'
    | '/_app/maintenance'
    | '/_app/marketing'
    | '/_app/mobile-app'
    | '/_app/mobile-control'
    | '/_app/payment-links'
    | '/_app/payment-pages'
    | '/_app/payments'
    | '/_app/payouts'
    | '/_app/pricing-plans'
    | '/_app/products'
    | '/_app/profile'
    | '/_app/purchases'
    | '/_app/sales'
    | '/_app/security'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/stock-adjustment'
    | '/_app/stock-transfers'
    | '/_app/system-health'
    | '/_app/transactions'
    | '/_app/users'
    | '/_app/webhooks'
    | '/_app/reports/inventory'
    | '/_app/reports/profit-loss'
    | '/_app/reports/purchases'
    | '/_app/reports/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-health': {
      id: '/_app/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AppSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-transfers': {
      id: '/_app/stock-transfers'
      path: '/stock-transfers'
      fullPath: '/stock-transfers'
      preLoaderRoute: typeof AppStockTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-adjustment': {
      id: '/_app/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment'
      preLoaderRoute: typeof AppStockAdjustmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing-plans': {
      id: '/_app/pricing-plans'
      path: '/pricing-plans'
      fullPath: '/pricing-plans'
      preLoaderRoute: typeof AppPricingPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment-pages': {
      id: '/_app/payment-pages'
      path: '/payment-pages'
      fullPath: '/payment-pages'
      preLoaderRoute: typeof AppPaymentPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment-links': {
      id: '/_app/payment-links'
      path: '/payment-links'
      fullPath: '/payment-links'
      preLoaderRoute: typeof AppPaymentLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile-control': {
      id: '/_app/mobile-control'
      path: '/mobile-control'
      fullPath: '/mobile-control'
      preLoaderRoute: typeof AppMobileControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile-app': {
      id: '/_app/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof AppMobileAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database-backup': {
      id: '/_app/database-backup'
      path: '/database-backup'
      fullPath: '/database-backup'
      preLoaderRoute: typeof AppDatabaseBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-control': {
      id: '/_app/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AppAccessControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/2fa': {
      id: '/_app/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof App2faRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/purchases': {
      id: '/_app/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AppReportsPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/profit-loss': {
      id: '/_app/reports/profit-loss'
      path: '/reports/profit-loss'
      fullPath: '/reports/profit-loss'
      preLoaderRoute: typeof AppReportsProfitLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/inventory': {
      id: '/_app/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AppReportsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  App2faRoute: typeof App2faRoute
  AppAccessControlRoute: typeof AppAccessControlRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabaseBackupRoute: typeof AppDatabaseBackupRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMobileAppRoute: typeof AppMobileAppRoute
  AppMobileControlRoute: typeof AppMobileControlRoute
  AppPaymentLinksRoute: typeof AppPaymentLinksRoute
  AppPaymentPagesRoute: typeof AppPaymentPagesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppPricingPlansRoute: typeof AppPricingPlansRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockAdjustmentRoute: typeof AppStockAdjustmentRoute
  AppStockTransfersRoute: typeof AppStockTransfersRoute
  AppSystemHealthRoute: typeof AppSystemHealthRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppReportsInventoryRoute: typeof AppReportsInventoryRoute
  AppReportsProfitLossRoute: typeof AppReportsProfitLossRoute
  AppReportsPurchasesRoute: typeof AppReportsPurchasesRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
}

const AppRouteChildren: AppRouteChildren = {
  App2faRoute: App2faRoute,
  AppAccessControlRoute: AppAccessControlRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabaseBackupRoute: AppDatabaseBackupRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppLogsRoute: AppLogsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMobileAppRoute: AppMobileAppRoute,
  AppMobileControlRoute: AppMobileControlRoute,
  AppPaymentLinksRoute: AppPaymentLinksRoute,
  AppPaymentPagesRoute: AppPaymentPagesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppPricingPlansRoute: AppPricingPlansRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockAdjustmentRoute: AppStockAdjustmentRoute,
  AppStockTransfersRoute: AppStockTransfersRoute,
  AppSystemHealthRoute: AppSystemHealthRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppReportsInventoryRoute: AppReportsInventoryRoute,
  AppReportsProfitLossRoute: AppReportsProfitLossRoute,
  AppReportsPurchasesRoute: AppReportsPurchasesRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
